### ISSUE TITLE
Isoler et figer les noeuds

### ISSUE THREAD

**Issue by clemsciences** [LouisLesueur/gods#1]
Bonjour,

Excellent ! Ces derniers temps, je me suis intéressé à comment afficher des relations entre personnages dans un récit et bien sûr les bibliothèques d'affichage de graphes font très bien le boulot. Cependant, j'ai pour le moment opté pour d3.js contrairement à vis.js qui a été retenu pour votre projet.

Ma question est : serait-il possible de figer les nœuds du graphe et aussi de cacher les nœuds sans liens à l'aide d'un bouton général de contrôle ? Ça permettrait de mieux lire les noms associés aux nœuds.

J'ai vu que vous planifiez de visualiser les familles sur une carte : vous pouvez vous inspirer de mon projet actuel https://github.com/clemsciences/nibelungen_map.

Cordialement

**Comment by LouisLesueur** [comment]
Bonjour,

Merci pour l'intérêt que vous portez au projet et pour les conseils !

Après une petite pause, je compte reprendre bientôt le développement de l'interface, et oui, je vais essayer de rendre l'arbre plus lisible, avec en particulier la possibilité d'appliquer des filtres et de visualiser des sous-arbres.

Je me souviens avoir choisi vis.js parce que je le trouvais assez simple à utiliser, et que j'ai pu monter cette première version assez vite avec, mais le choix n'est pas encore définitif.

Je vais regarder votre projet de ce pas !

Bien cordialement.
